/**
 * @module toolbox-talks
 *
 * Domain types for the Toolbox Talks module (`MODULE_TOOLBOX_TALKS`): the
 * entity as the backend publishes it, its request shapes, and the parser
 * that turns a raw payload into the typed entity.
 *
 * Generated by `bun run scaffold:domain toolbox-talks`. Replace the
 * placeholder fields with the module's real ones; keep the parser
 * non-strict so a field the backend adds later never breaks this client.
 */

import { z } from 'zod';
import {
  backendDate,
  nullableNumber,
  nullableString,
} from '../../lib/validation/backend-schema';

/** A Toolbox Talks record as published by the backend. */
export interface ToolboxTalks {
  /** Stable identifier. */
  id: string;
  /** Display name. */
  name: string;
  /** Free-text description, empty when the backend sends none. */
  description: string;
  /** Owning project, when the record is project scoped. */
  projectId?: number;
  /** ISO timestamp of creation, when the backend sends one. */
  createdAt?: string;
  /** ISO timestamp of the last update, when the backend sends one. */
  updatedAt?: string;
}

/** Body of `POST /toolbox-talks/web`. */
export interface CreateToolboxTalksRequest {
  name: string;
  description?: string;
  projectId?: number;
}

/** Body of `PUT /toolbox-talks/web/{id}`. Every field is optional. */
export type UpdateToolboxTalksRequest = Partial<CreateToolboxTalksRequest>;

/** Query parameters of `GET /toolbox-talks/web`. */
export interface ToolboxTalksListParams {
  projectId?: number;
  /** 0-based page index. */
  page?: number;
  size?: number;
}

/** A page of records, the backend's own envelope. */
export interface ToolboxTalksPage {
  content: ToolboxTalks[];
  /** 0-based page index. */
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}

const ToolboxTalksResponseSchema = z.object({
  id: z.union([z.string(), z.number()]),
  name: nullableString,
  description: nullableString,
  projectId: nullableNumber,
  createdAt: backendDate,
  updatedAt: backendDate,
});

const ToolboxTalksPageSchema = z.object({
  content: z.array(z.unknown()).nullish(),
  page: nullableNumber,
  number: nullableNumber,
  size: nullableNumber,
  totalElements: nullableNumber,
  totalPages: nullableNumber,
});

/**
 * Parses a raw API payload into a typed {@link ToolboxTalks}.
 *
 * Non-strict: unknown keys are stripped rather than rejected. Only `id` is
 * required; every other field defaults when absent.
 *
 * @throws {Error} If `id` is missing.
 */
export function parseToolboxTalks(json: unknown): ToolboxTalks {
  const raw = ToolboxTalksResponseSchema.parse(json);
  return {
    id: String(raw.id),
    name: raw.name ?? '',
    description: raw.description ?? '',
    projectId: raw.projectId ?? undefined,
    createdAt: raw.createdAt ?? undefined,
    updatedAt: raw.updatedAt ?? undefined,
  };
}

/**
 * Parses a Spring-style page of records. Accepts either `page` or `number`
 * for the index, since the backend has published both spellings.
 */
export function parseToolboxTalksPage(json: unknown): ToolboxTalksPage {
  const raw = ToolboxTalksPageSchema.parse(json);
  const content = (raw.content ?? []).map((item) => parseToolboxTalks(item));
  return {
    content,
    page: raw.page ?? raw.number ?? 0,
    size: raw.size ?? content.length,
    totalElements: raw.totalElements ?? content.length,
    totalPages: raw.totalPages ?? (content.length > 0 ? 1 : 0),
  };
}
