/**
 * Public-API snapshot generator / checker.
 *
 * `@tornotron/echno-core` exposes its public surface through the `exports` map in
 * package.json: the root barrel (`.`) plus wildcard subpaths (`<name>/types`,
 * `<name>/services`, `<name>/hooks`, `<name>/hooks/keys`). This script walks every
 * one of those entry points, records the exported symbol names (marking `@deprecated`
 * and `@internal` ones), and writes them to `etc/public-api.md`.
 *
 *   bun scripts/api-snapshot.ts            # regenerate etc/public-api.md
 *   bun scripts/api-snapshot.ts --check    # fail if the committed snapshot is stale
 *
 * The committed snapshot is the reviewed public contract: any add/remove of a public
 * symbol shows up as a diff, so a breaking change cannot slip in unnoticed. See
 * docs/API-STABILITY.md for how this backs the semver commitment.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as ts from 'typescript';

const ROOT = path.resolve(import.meta.dir, '..');
const SRC = path.join(ROOT, 'src');
const SNAPSHOT = path.join(ROOT, 'etc', 'public-api.md');

/** Resolve every public entry point to `{ subpath, file }`, mirroring package.json `exports`. */
function collectEntries(): { subpath: string; file: string }[] {
  const entries: { subpath: string; file: string }[] = [];
  const add = (subpath: string, file: string) => {
    if (fs.existsSync(file)) entries.push({ subpath, file });
  };

  add('.', path.join(SRC, 'index.ts'));

  // `./*/types` -> src/types/<name>/index.ts
  for (const name of dirsIn(path.join(SRC, 'types'))) {
    add(`${name}/types`, path.join(SRC, 'types', name, 'index.ts'));
  }
  // `./*/services` -> src/services/<name>-service.ts
  for (const f of filesIn(path.join(SRC, 'services'))) {
    const m = f.match(/^(.*)-service\.ts$/);
    if (m) add(`${m[1]}/services`, path.join(SRC, 'services', f));
  }
  // `./*/hooks` and `./*/hooks/keys`
  for (const name of dirsIn(path.join(SRC, 'hooks'))) {
    add(`${name}/hooks`, path.join(SRC, 'hooks', name, 'index.ts'));
    add(`${name}/hooks/keys`, path.join(SRC, 'hooks', name, 'keys.ts'));
  }

  entries.sort((a, b) => a.subpath.localeCompare(b.subpath));
  return entries;
}

function dirsIn(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

function filesIn(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).filter((d) => d.isFile()).map((d) => d.name);
}

function loadCompilerOptions(): ts.CompilerOptions {
  const configPath = path.join(ROOT, 'tsconfig.json');
  const read = ts.readConfigFile(configPath, ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(read.config, ts.sys, ROOT);
  return { ...parsed.options, noEmit: true };
}

/** For a symbol, return a suffix marker if it carries a stability JSDoc tag. */
function stabilityMarker(symbol: ts.Symbol, checker: ts.TypeChecker): string {
  const tags = symbol.getJsDocTags(checker).map((t) => t.name.toLowerCase());
  if (tags.includes('deprecated')) return '  [deprecated]';
  if (tags.includes('internal')) return '  [internal]';
  return '';
}

function generate(): string {
  const entries = collectEntries();
  const options = loadCompilerOptions();
  const program = ts.createProgram(
    entries.map((e) => e.file),
    options,
  );
  const checker = program.getTypeChecker();

  const lines: string[] = [
    '# @tornotron/echno-core — public API surface',
    '',
    '<!-- GENERATED by scripts/api-snapshot.ts. Do not edit by hand.',
    '     Run `bun run api:snapshot` after an intended public-API change and commit the diff.',
    '     See docs/API-STABILITY.md. -->',
    '',
    `Entry points: ${entries.length}`,
    '',
  ];

  for (const { subpath, file } of entries) {
    const sf = program.getSourceFile(file);
    const moduleSymbol = sf && checker.getSymbolAtLocation(sf);
    const exported = moduleSymbol ? checker.getExportsOfModule(moduleSymbol) : [];
    const names = exported
      .map((s) => `${s.getName()}${stabilityMarker(s, checker)}`)
      .sort((a, b) => a.localeCompare(b));

    lines.push(`## \`@tornotron/echno-core${subpath === '.' ? '' : '/' + subpath}\``, '');
    if (names.length === 0) {
      lines.push('_(no exports)_', '');
    } else {
      for (const n of names) lines.push(`- ${n}`);
      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}

function main() {
  const check = process.argv.includes('--check');
  const next = generate();

  if (check) {
    const current = fs.existsSync(SNAPSHOT) ? fs.readFileSync(SNAPSHOT, 'utf8') : '';
    if (current !== next) {
      console.error(
        'Public API snapshot is stale.\n' +
          'The exported surface changed but etc/public-api.md was not updated.\n' +
          'If this change is intended, run `bun run api:snapshot` and commit etc/public-api.md.\n' +
          'If it is not, you introduced an unintended public-API change (a potential semver break).',
      );
      process.exit(1);
    }
    console.log('Public API snapshot is up to date.');
    return;
  }

  fs.mkdirSync(path.dirname(SNAPSHOT), { recursive: true });
  fs.writeFileSync(SNAPSHOT, next);
  console.log(`Wrote ${path.relative(ROOT, SNAPSHOT)} (${next.split('\n').length} lines).`);
}

main();
